### 픽셀

이미지 데이터를 컴퓨터 내부에 저장하는 요소
* Picture Element의 줄임말
* 이미지의 최소 해상도 단위 (화소)
* 네모칸이 이미지의 색 정보를 **수 형태**로 담고 있음

### 비트맵 이미지

* 화소 단위로 이미지를 저장한 것
* 확장자: `bmp` `gif` `jpeg`
* 장단점
    * 사실적인 묘사가 가능
    * 고해상도 이미지의 용량 문제
    * 확대하면 각진형태 (픽셀)이 두드러져 보임

# [NumPy](www.numpy.org)

* 이미지를 연산할 때 사용되는 **라이브러리**
* Numpy는 사각형, 차원의 정보를 다루기 때문에 **다차원 행렬**을 다룰 때 용이함
* **덧셈과 뺄셈** 연산자로 행렬의 연산을 수행 할 수 있음



### Numpy: 사용방법

* import `라이브러리` as `별칭`

    * `import numpy as np`

* 배열 정의

    * `np.array()`

* 배열 출력

    * `print()`

* 배열의 모양 출력
    * `print(array.shape)`
    * 예) 1행 3열 배열일 경우 출력값: (3,)

* 배열의 차원 출력
    * 차원: 몇 가지 정보에 대해서 해당 정보를 출력 할 수 있는가?
    * `print(array.ndim)`
    * number dimension


In [14]:
import numpy as np

# 일차원 배열
arr = np.array([1,2,3])
print(arr)  # [1 2 3]
print(arr.shape)  # (3,)
print(arr.ndim)  # 1


[1 2 3]
(3,)
1


### Numpy: 행렬의 연산



In [18]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([
    [1,2,3],
    [4,5,6]
])

# 합차
sum_ab = a + b
print(sum_ab)   # 행렬 출력
print(sum_ab.shape) # 행렬 개수
print(sum_ab.ndim)  # 차원 개수

# 실수배
div_ab = 0.5 * a
print(div_ab)
print(div_ab.shape)
print(div_ab.ndim)

[[ 2  4  6]
 [ 8 10 12]]
(2, 3)
2
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
(2, 3)
2


# 터틀 그래픽

가상의 거북을 원하는대로 움직이며 복잡한 모양을 만드는 간단한 프로그래밍 툴

실제 저장된 행렬을 시각화하기 위해 사용한다

### turtle: 사용방법


* `import turtle`
    * 파이썬에 포함되어있지만 모듈을 사용하기 위해선 import 필요
* 색 지정
    * 첫번째 인자는 선의 색, 두번째 인자는 채우기 색
    * `turtle.color("black", "red")`
* 원 그리기
    * `turtle.circle(80, steps= 4)`
        * 80: 반지름 길이
        * 4: 네번만에 그려라
* 채우기 시작, 끝
    * `turtle.begin_fill()`
    * `turtle.end_fill()`

* turtle의 방향
    * `turtle.setheading(90)`
        * turtle의 방향을 반시계 방향을 90도 이동
    * `turtle.heading`
        * 현재 turtle의 방향. print와 함께 사용

* turtle을 특정 좌표로 이동하기
    * `turtle.goto(200, 0)`
        * 1사분면 200, 0으로 이동

* turtle이 펜을 들어 자취를 남기지 않게 하기
    * `turtle.penup()`

In [48]:
import turtle

turtle.color("black", "red")
turtle.begin_fill()
turtle.circle(80)
turtle.circle(80, steps =4)
turtle.end_fill()

In [49]:
turtle.setheading(90)
print(turtle.heading()) # 90.0

90.0


In [50]:
turtle.goto(200, 0)

In [51]:
turtle.penup()
turtle.goto(-200,0)

In [52]:
turtle.getscreen()._root.mainloop()

# turtle 프로그램의 실행을 보장
# 위 명령어를 마지막에 사용하여 프로그램을 제대로 종료 할 것